import { DiscoverDestination } from "./types";

/**
 * Mock destinations reachable from the New York City region, used to
 * populate /discover. Replace with a real recommendation source in a
 * later phase — for now every field is hand-authored placeholder data.
 */
export const discoverDestinations: DiscoverDestination[] = [
  {
    id: "bear-mountain-state-park",
    name: "Bear Mountain State Park",
    region: "Hudson Highlands, NY",
    shortDescription:
      "A classic first hike with summit views over the Hudson, plus a lake and picnic areas for a slower day.",
    activities: ["hiking", "camping"],
    difficulty: "moderate",
    estimatedTravelTimeMinutes: 70,
    transportationOptions: ["car", "no-car"],
    carFreeFriendly: true,
    estimatedTripCost: 70,
    trailDistanceMiles: 4.5,
    rating: 4.6,
    adventureMatchScore: 94,
    imageGradient: "trail-1",
  },
  {
    id: "harriman-state-park",
    name: "Harriman State Park",
    region: "Southfields, NY",
    shortDescription:
      "Sprawling trail network with quiet lakes — easy to build a route from a short loop to an all-day traverse.",
    activities: ["hiking", "camping"],
    difficulty: "moderate",
    estimatedTravelTimeMinutes: 75,
    transportationOptions: ["car", "no-car"],
    carFreeFriendly: true,
    estimatedTripCost: 65,
    trailDistanceMiles: 6.2,
    rating: 4.5,
    adventureMatchScore: 90,
    imageGradient: "trail-2",
  },
  {
    id: "breakneck-ridge",
    name: "Breakneck Ridge",
    region: "Cold Spring, NY",
    shortDescription:
      "Steep scrambles and near-constant Hudson River views — the region's most rewarded workout.",
    activities: ["hiking"],
    difficulty: "hard",
    estimatedTravelTimeMinutes: 90,
    transportationOptions: ["car", "no-car"],
    carFreeFriendly: true,
    estimatedTripCost: 45,
    trailDistanceMiles: 3.7,
    rating: 4.7,
    adventureMatchScore: 88,
    imageGradient: "trail-3",
  },
  {
    id: "minnewaska-state-park",
    name: "Minnewaska State Park Preserve",
    region: "Kerhonkson, NY",
    shortDescription:
      "Sky-blue lakes and cliffside carriage roads through the Shawangunk Ridge — beginner-friendly and scenic.",
    activities: ["hiking"],
    difficulty: "easy",
    estimatedTravelTimeMinutes: 110,
    transportationOptions: ["car"],
    carFreeFriendly: false,
    estimatedTripCost: 80,
    trailDistanceMiles: 4.5,
    rating: 4.6,
    adventureMatchScore: 78,
    imageGradient: "trail-1",
  },
  {
    id: "mohonk-preserve",
    name: "Mohonk Preserve",
    region: "New Paltz, NY",
    shortDescription:
      "Rock-climbing meccas and quiet carriage roads beneath the Mohonk Mountain House towers.",
    activities: ["hiking"],
    difficulty: "moderate",
    estimatedTravelTimeMinutes: 115,
    transportationOptions: ["car"],
    carFreeFriendly: false,
    estimatedTripCost: 90,
    trailDistanceMiles: 5.0,
    rating: 4.8,
    adventureMatchScore: 82,
    imageGradient: "trail-2",
  },
  {
    id: "catskill-mountains",
    name: "Catskill Mountains",
    region: "Catskill Park, NY",
    shortDescription:
      "High Peaks, waterfalls and backcountry camping for a proper weekend away from the city.",
    activities: ["hiking", "camping"],
    difficulty: "hard",
    estimatedTravelTimeMinutes: 140,
    transportationOptions: ["car"],
    carFreeFriendly: false,
    estimatedTripCost: 120,
    trailDistanceMiles: 8.0,
    rating: 4.5,
    adventureMatchScore: 75,
    imageGradient: "trail-3",
  },
  {
    id: "delaware-water-gap",
    name: "Delaware Water Gap",
    region: "Pennsylvania / New Jersey border",
    shortDescription:
      "River bends beneath forested ridgelines, with room for a riverside camp and an easy morning paddle.",
    activities: ["hiking", "camping"],
    difficulty: "moderate",
    estimatedTravelTimeMinutes: 95,
    transportationOptions: ["car"],
    carFreeFriendly: false,
    estimatedTripCost: 100,
    trailDistanceMiles: 6.5,
    rating: 4.4,
    adventureMatchScore: 71,
    imageGradient: "trail-1",
  },
  {
    id: "fire-island-national-seashore",
    name: "Fire Island National Seashore",
    region: "Long Island, NY",
    shortDescription:
      "Car-free barrier island with dune trails, a lighthouse walk, and beachside camping by ferry.",
    activities: ["hiking", "camping"],
    difficulty: "easy",
    estimatedTravelTimeMinutes: 120,
    transportationOptions: ["no-car"],
    carFreeFriendly: true,
    estimatedTripCost: 130,
    trailDistanceMiles: 3.0,
    rating: 4.3,
    adventureMatchScore: 68,
    imageGradient: "trail-2",
  },
];
