import { TripPlan } from "./types";

const CHECKLIST = [
  "Water",
  "Food/snacks",
  "Weather-appropriate layers",
  "Trail shoes",
  "Phone/battery",
  "Offline map",
];

/**
 * Mock door-to-trail trip plans, keyed by `adventureId` (matches
 * `DiscoverDestination.id` in discover-destinations.ts). One plan per
 * adventure currently available in /discover. Replace with a real
 * itinerary-generation source (transit/weather/maps APIs) in a later
 * phase — every field here is hand-authored placeholder data.
 */
export const tripPlans: TripPlan[] = [
  {
    adventureId: "bear-mountain-state-park",
    tripDate: "Saturday, Oct 18",
    transportationModeLabel: "Train + Shuttle",
    summary:
      "A train-and-shuttle day trip to Bear Mountain, with time for the Major Welch Trail and a lakeside lunch.",
    departure: "7:15 AM",
    arrivalAtTrail: "9:45 AM",
    trailStartTime: "10:00 AM",
    returnTime: "2:15 PM",
    estimatedArrivalHome: "4:30 PM",
    totalTravelTimeMinutes: 100,
    timeline: [
      { id: "s1", time: "7:15 AM", title: "Leave home", kind: "depart", location: "New York, NY" },
      { id: "s2", time: "7:45 AM", title: "Arrive at Grand Central", kind: "arrive" },
      { id: "s3", time: "8:05 AM", title: "Metro-North train", kind: "transit", detail: "Grand Central → Peekskill", durationMinutes: 67 },
      { id: "s4", time: "9:12 AM", title: "Arrive Peekskill", kind: "arrive" },
      { id: "s5", time: "9:25 AM", title: "Local shuttle", kind: "transit", detail: "Peekskill → Bear Mountain", durationMinutes: 20 },
      { id: "s6", time: "9:45 AM", title: "Arrive at trailhead", kind: "arrive" },
      { id: "s7", time: "10:00 AM", title: "Start hike", kind: "activity", detail: "Major Welch Trail", durationMinutes: 120 },
      { id: "s8", time: "1:00 PM", title: "Finish hike / lunch", kind: "activity", note: "Lakeside picnic tables near the inn." },
      { id: "s9", time: "2:15 PM", title: "Begin return trip", kind: "return" },
      { id: "s10", time: "4:30 PM", title: "Arrive home", kind: "arrive" },
    ],
    transportationLegs: [
      {
        id: "leg1",
        mode: "transit",
        label: "Metro-North Hudson Line",
        from: "Grand Central",
        to: "Peekskill",
        departure: "8:05 AM",
        arrival: "9:12 AM",
        durationMinutes: 67,
        fare: 15,
        transferInfo: "No transfer — direct train.",
      },
      {
        id: "leg2",
        mode: "shuttle",
        label: "Local shuttle to Bear Mountain",
        from: "Peekskill",
        to: "Bear Mountain Inn",
        departure: "9:25 AM",
        arrival: "9:45 AM",
        durationMinutes: 20,
        fare: 10,
        transferInfo: "Seasonal weekend shuttle, meets the train at the station.",
      },
    ],
    trailDayPlan: {
      trailName: "Major Welch Trail",
      trailDistanceMiles: 2.6,
      estimatedDurationMinutes: 120,
      difficulty: "moderate",
      elevationGainFeet: 1140,
      suggestedStartTime: "10:00 AM",
      suggestedFinishTime: "1:00 PM",
      lunchWindow: "12:30 – 1:00 PM",
      checklist: CHECKLIST,
    },
    costBreakdown: [
      { label: "Transit", amount: 30 },
      { label: "Local transfer", amount: 20 },
      { label: "Food", amount: 15 },
      { label: "Park/trail fees", amount: 0 },
      { label: "Buffer", amount: 5 },
    ],
    weatherWindows: [
      { label: "Morning", tempF: 50, condition: "Clear" },
      { label: "Afternoon", tempF: 58, condition: "Light rain" },
    ],
    weatherRecommendation:
      "Cool, clear start with a chance of afternoon showers — bring a light rain layer.",
  },
  {
    adventureId: "harriman-state-park",
    tripDate: "Saturday, Oct 18",
    transportationModeLabel: "Bus",
    summary:
      "A bus day trip into Harriman, with a full loop around Pine Meadow Lake.",
    departure: "7:30 AM",
    arrivalAtTrail: "9:50 AM",
    trailStartTime: "10:00 AM",
    returnTime: "2:00 PM",
    estimatedArrivalHome: "4:30 PM",
    totalTravelTimeMinutes: 110,
    timeline: [
      { id: "s1", time: "7:30 AM", title: "Leave home", kind: "depart", location: "New York, NY" },
      { id: "s2", time: "8:00 AM", title: "Arrive Port Authority", kind: "arrive" },
      { id: "s3", time: "8:15 AM", title: "Short Line bus", kind: "transit", detail: "Port Authority → Sloatsburg", durationMinutes: 75 },
      { id: "s4", time: "9:30 AM", title: "Arrive Sloatsburg", kind: "arrive" },
      { id: "s5", time: "9:35 AM", title: "Walk to trailhead", kind: "transit", durationMinutes: 15 },
      { id: "s6", time: "9:50 AM", title: "Arrive at trailhead", kind: "arrive" },
      { id: "s7", time: "10:00 AM", title: "Start hike", kind: "activity", detail: "Pine Meadow Loop", durationMinutes: 180 },
      { id: "s8", time: "1:00 PM", title: "Finish hike / lunch", kind: "activity", note: "Picnic spots along Pine Meadow Lake." },
      { id: "s9", time: "2:00 PM", title: "Begin return trip", kind: "return" },
      { id: "s10", time: "4:30 PM", title: "Arrive home", kind: "arrive" },
    ],
    transportationLegs: [
      {
        id: "leg1",
        mode: "transit",
        label: "Short Line Bus",
        from: "Port Authority",
        to: "Sloatsburg",
        departure: "8:15 AM",
        arrival: "9:30 AM",
        durationMinutes: 75,
        fare: 14,
        transferInfo: "No transfer — direct bus.",
      },
      {
        id: "leg2",
        mode: "walk",
        label: "Walk to trailhead",
        from: "Sloatsburg bus stop",
        to: "Reeves Brook trailhead",
        departure: "9:30 AM",
        arrival: "9:50 AM",
        durationMinutes: 15,
      },
    ],
    trailDayPlan: {
      trailName: "Pine Meadow Loop",
      trailDistanceMiles: 6.2,
      estimatedDurationMinutes: 180,
      difficulty: "moderate",
      elevationGainFeet: 980,
      suggestedStartTime: "10:00 AM",
      suggestedFinishTime: "1:00 PM",
      lunchWindow: "12:30 – 1:00 PM",
      checklist: CHECKLIST,
    },
    costBreakdown: [
      { label: "Transit", amount: 28 },
      { label: "Food", amount: 22 },
      { label: "Park/trail fees", amount: 5 },
      { label: "Buffer", amount: 10 },
    ],
    weatherWindows: [
      { label: "Morning", tempF: 51, condition: "Clear" },
      { label: "Afternoon", tempF: 59, condition: "Light rain" },
    ],
    weatherRecommendation:
      "Mild and clear early on — pack a light rain shell in case the afternoon showers arrive.",
  },
  {
    adventureId: "breakneck-ridge",
    tripDate: "Saturday, Oct 18",
    transportationModeLabel: "Train",
    summary:
      "A direct train trip to Breakneck Ridge for a short, hard climb with big Hudson views.",
    departure: "7:45 AM",
    arrivalAtTrail: "9:20 AM",
    trailStartTime: "9:30 AM",
    returnTime: "1:30 PM",
    estimatedArrivalHome: "3:15 PM",
    totalTravelTimeMinutes: 95,
    timeline: [
      { id: "s1", time: "7:45 AM", title: "Leave home", kind: "depart", location: "New York, NY" },
      { id: "s2", time: "8:10 AM", title: "Arrive at Grand Central", kind: "arrive" },
      { id: "s3", time: "8:25 AM", title: "Metro-North train", kind: "transit", detail: "Grand Central → Breakneck Ridge", durationMinutes: 75 },
      { id: "s4", time: "9:20 AM", title: "Arrive at trailhead", kind: "arrive", note: "Trailhead is right across the tracks from the platform." },
      { id: "s5", time: "9:30 AM", title: "Start hike", kind: "activity", detail: "Breakneck Ridge Trail", durationMinutes: 180 },
      { id: "s6", time: "12:30 PM", title: "Finish hike / lunch", kind: "activity", note: "Cold Spring village has a few good lunch spots." },
      { id: "s7", time: "1:30 PM", title: "Begin return trip", kind: "return" },
      { id: "s8", time: "3:15 PM", title: "Arrive home", kind: "arrive" },
    ],
    transportationLegs: [
      {
        id: "leg1",
        mode: "transit",
        label: "Metro-North Hudson Line",
        from: "Grand Central",
        to: "Breakneck Ridge (seasonal stop)",
        departure: "8:25 AM",
        arrival: "9:20 AM",
        durationMinutes: 75,
        fare: 17,
        transferInfo: "Seasonal weekend stop — confirm the train makes this station before you go.",
      },
    ],
    trailDayPlan: {
      trailName: "Breakneck Ridge Trail",
      trailDistanceMiles: 3.7,
      estimatedDurationMinutes: 180,
      difficulty: "hard",
      elevationGainFeet: 1420,
      suggestedStartTime: "9:30 AM",
      suggestedFinishTime: "12:30 PM",
      lunchWindow: "12:30 – 1:15 PM in Cold Spring",
      checklist: CHECKLIST,
    },
    costBreakdown: [
      { label: "Transit", amount: 25 },
      { label: "Food", amount: 15 },
      { label: "Park/trail fees", amount: 0 },
      { label: "Buffer", amount: 5 },
    ],
    weatherWindows: [
      { label: "Morning", tempF: 49, condition: "Windy" },
      { label: "Afternoon", tempF: 57, condition: "Light rain" },
    ],
    weatherRecommendation:
      "Windy and cool on the exposed ridge in the morning — a windproof layer matters more than a warm one.",
  },
  {
    adventureId: "minnewaska-state-park",
    tripDate: "Saturday, Oct 18",
    transportationModeLabel: "Driving",
    summary:
      "A driving day trip to Minnewaska for an easy, scenic loop around the sky lake.",
    departure: "7:00 AM",
    arrivalAtTrail: "8:50 AM",
    trailStartTime: "9:00 AM",
    returnTime: "12:30 PM",
    estimatedArrivalHome: "2:20 PM",
    totalTravelTimeMinutes: 110,
    timeline: [
      { id: "s1", time: "7:00 AM", title: "Leave home", kind: "depart", location: "New York, NY" },
      { id: "s2", time: "8:50 AM", title: "Arrive at trailhead parking", kind: "arrive", detail: "Drive via I-87 and NY-299", durationMinutes: 110 },
      { id: "s3", time: "9:00 AM", title: "Start hike", kind: "activity", detail: "Lake Minnewaska Carriage Loop", durationMinutes: 120 },
      { id: "s4", time: "11:00 AM", title: "Finish hike / lunch", kind: "activity", note: "Lake overlooks make a good picnic stop." },
      { id: "s5", time: "12:30 PM", title: "Begin return trip", kind: "return" },
      { id: "s6", time: "2:20 PM", title: "Arrive home", kind: "arrive" },
    ],
    transportationLegs: [
      {
        id: "leg1",
        mode: "driving",
        label: "Drive via I-87 and NY-299",
        from: "New York, NY",
        to: "Minnewaska State Park Preserve",
        departure: "7:00 AM",
        arrival: "8:50 AM",
        durationMinutes: 110,
        distanceMiles: 95,
        parkingInfo: "Pay lot at the main entrance, $10 per vehicle.",
        estimatedDriveCost: 35,
      },
    ],
    trailDayPlan: {
      trailName: "Lake Minnewaska Carriage Loop",
      trailDistanceMiles: 4.5,
      estimatedDurationMinutes: 120,
      difficulty: "easy",
      elevationGainFeet: 300,
      suggestedStartTime: "9:00 AM",
      suggestedFinishTime: "11:00 AM",
      lunchWindow: "11:00 – 11:45 AM",
      checklist: CHECKLIST,
    },
    costBreakdown: [
      { label: "Driving (fuel/tolls)", amount: 35 },
      { label: "Parking", amount: 10 },
      { label: "Food", amount: 25 },
      { label: "Buffer", amount: 10 },
    ],
    weatherWindows: [
      { label: "Morning", tempF: 52, condition: "Sunny" },
      { label: "Afternoon", tempF: 60, condition: "Partly cloudy" },
    ],
    weatherRecommendation:
      "A clear, mild day throughout — light layers are enough, no rain gear needed.",
  },
  {
    adventureId: "mohonk-preserve",
    tripDate: "Saturday, Oct 18",
    transportationModeLabel: "Driving",
    summary:
      "A driving day trip to Mohonk for a moderate carriage-road loop beneath the Mountain House.",
    departure: "6:45 AM",
    arrivalAtTrail: "8:40 AM",
    trailStartTime: "9:00 AM",
    returnTime: "1:00 PM",
    estimatedArrivalHome: "2:55 PM",
    totalTravelTimeMinutes: 115,
    timeline: [
      { id: "s1", time: "6:45 AM", title: "Leave home", kind: "depart", location: "New York, NY" },
      { id: "s2", time: "8:40 AM", title: "Arrive at day-use lot", kind: "arrive", detail: "Drive via NY-299", durationMinutes: 115 },
      { id: "s3", time: "9:00 AM", title: "Start hike", kind: "activity", detail: "Mohonk Lake Carriage Loop", durationMinutes: 150 },
      { id: "s4", time: "11:30 AM", title: "Finish hike / lunch", kind: "activity", note: "Lakeside benches near the Mountain House." },
      { id: "s5", time: "1:00 PM", title: "Begin return trip", kind: "return" },
      { id: "s6", time: "2:55 PM", title: "Arrive home", kind: "arrive" },
    ],
    transportationLegs: [
      {
        id: "leg1",
        mode: "driving",
        label: "Drive via NY-299",
        from: "New York, NY",
        to: "Mohonk Preserve",
        departure: "6:45 AM",
        arrival: "8:40 AM",
        durationMinutes: 115,
        distanceMiles: 100,
        parkingInfo: "Day-use lot fee is $25 per vehicle on weekends.",
        estimatedDriveCost: 35,
      },
    ],
    trailDayPlan: {
      trailName: "Mohonk Lake Carriage Loop",
      trailDistanceMiles: 5.0,
      estimatedDurationMinutes: 150,
      difficulty: "moderate",
      elevationGainFeet: 600,
      suggestedStartTime: "9:00 AM",
      suggestedFinishTime: "11:30 AM",
      lunchWindow: "11:30 AM – 12:15 PM",
      checklist: CHECKLIST,
    },
    costBreakdown: [
      { label: "Driving (fuel/tolls)", amount: 35 },
      { label: "Parking / day-use fee", amount: 25 },
      { label: "Food", amount: 20 },
      { label: "Buffer", amount: 10 },
    ],
    weatherWindows: [
      { label: "Morning", tempF: 51, condition: "Sunny" },
      { label: "Afternoon", tempF: 59, condition: "Partly cloudy" },
    ],
    weatherRecommendation:
      "Sunny and mild — a light layer for the morning drive is all you'll need.",
  },
  {
    adventureId: "catskill-mountains",
    tripDate: "Saturday, Oct 18",
    transportationModeLabel: "Driving",
    summary:
      "A longer driving day into the Catskills, with time for Kaaterskill Falls and the North-South Lake area.",
    departure: "6:00 AM",
    arrivalAtTrail: "8:20 AM",
    trailStartTime: "8:30 AM",
    returnTime: "3:00 PM",
    estimatedArrivalHome: "5:20 PM",
    totalTravelTimeMinutes: 140,
    timeline: [
      { id: "s1", time: "6:00 AM", title: "Leave home", kind: "depart", location: "New York, NY" },
      { id: "s2", time: "8:20 AM", title: "Arrive at trailhead", kind: "arrive", detail: "Drive via NY Thruway to NY-23A", durationMinutes: 140 },
      { id: "s3", time: "8:30 AM", title: "Start hike", kind: "activity", detail: "Kaaterskill Falls Trail", durationMinutes: 90 },
      { id: "s4", time: "10:00 AM", title: "Finish hike / lunch", kind: "activity" },
      { id: "s5", time: "10:45 AM", title: "Explore North-South Lake", kind: "activity", note: "Extra time to swim or relax before the drive back." },
      { id: "s6", time: "3:00 PM", title: "Begin return trip", kind: "return" },
      { id: "s7", time: "5:20 PM", title: "Arrive home", kind: "arrive" },
    ],
    transportationLegs: [
      {
        id: "leg1",
        mode: "driving",
        label: "Drive via NY Thruway and NY-23A",
        from: "New York, NY",
        to: "Catskill Park",
        departure: "6:00 AM",
        arrival: "8:20 AM",
        durationMinutes: 140,
        distanceMiles: 120,
        parkingInfo: "Trailhead lots vary by peak; arrive early on weekends.",
        estimatedDriveCost: 45,
      },
    ],
    trailDayPlan: {
      trailName: "Kaaterskill Falls Trail",
      trailDistanceMiles: 2.4,
      estimatedDurationMinutes: 90,
      difficulty: "moderate",
      elevationGainFeet: 500,
      suggestedStartTime: "8:30 AM",
      suggestedFinishTime: "10:00 AM",
      lunchWindow: "10:00 – 10:45 AM",
      checklist: CHECKLIST,
    },
    costBreakdown: [
      { label: "Driving (fuel/tolls)", amount: 45 },
      { label: "Parking / trail fees", amount: 15 },
      { label: "Food", amount: 40 },
      { label: "Buffer", amount: 20 },
    ],
    weatherWindows: [
      { label: "Morning", tempF: 42, condition: "Cloudy" },
      { label: "Afternoon", tempF: 50, condition: "Rain" },
    ],
    weatherRecommendation:
      "Cold start with rain likely by afternoon — bring a real waterproof layer and warm socks.",
  },
  {
    adventureId: "delaware-water-gap",
    tripDate: "Saturday, Oct 18",
    transportationModeLabel: "Driving",
    summary:
      "A driving day trip to the Water Gap for a steep climb up Mount Tammany with river views the whole way.",
    departure: "7:15 AM",
    arrivalAtTrail: "8:50 AM",
    trailStartTime: "9:00 AM",
    returnTime: "1:00 PM",
    estimatedArrivalHome: "2:35 PM",
    totalTravelTimeMinutes: 95,
    timeline: [
      { id: "s1", time: "7:15 AM", title: "Leave home", kind: "depart", location: "New York, NY" },
      { id: "s2", time: "8:50 AM", title: "Arrive at trailhead parking", kind: "arrive", detail: "Drive via I-80", durationMinutes: 95 },
      { id: "s3", time: "9:00 AM", title: "Start hike", kind: "activity", detail: "Mount Tammany Trail", durationMinutes: 150 },
      { id: "s4", time: "11:30 AM", title: "Finish hike / lunch", kind: "activity" },
      { id: "s5", time: "1:00 PM", title: "Begin return trip", kind: "return" },
      { id: "s6", time: "2:35 PM", title: "Arrive home", kind: "arrive" },
    ],
    transportationLegs: [
      {
        id: "leg1",
        mode: "driving",
        label: "Drive via I-80",
        from: "New York, NY",
        to: "Delaware Water Gap",
        departure: "7:15 AM",
        arrival: "8:50 AM",
        durationMinutes: 95,
        distanceMiles: 80,
        parkingInfo: "Free lots at the main trailheads.",
        estimatedDriveCost: 40,
      },
    ],
    trailDayPlan: {
      trailName: "Mount Tammany Trail",
      trailDistanceMiles: 3.5,
      estimatedDurationMinutes: 150,
      difficulty: "hard",
      elevationGainFeet: 1200,
      suggestedStartTime: "9:00 AM",
      suggestedFinishTime: "11:30 AM",
      lunchWindow: "11:30 AM – 12:15 PM",
      checklist: CHECKLIST,
    },
    costBreakdown: [
      { label: "Driving (fuel/tolls)", amount: 40 },
      { label: "Food", amount: 35 },
      { label: "Buffer", amount: 25 },
    ],
    weatherWindows: [
      { label: "Morning", tempF: 53, condition: "Sunny" },
      { label: "Afternoon", tempF: 64, condition: "Sunny" },
    ],
    weatherRecommendation:
      "Clear and mild all day — sun protection matters more than extra layers.",
  },
  {
    adventureId: "fire-island-national-seashore",
    tripDate: "Saturday, Oct 18",
    transportationModeLabel: "Train + Ferry",
    summary:
      "A car-free day on Fire Island: LIRR to Sayville, then the ferry across to the trailhead.",
    departure: "6:30 AM",
    arrivalAtTrail: "9:15 AM",
    trailStartTime: "9:30 AM",
    returnTime: "1:00 PM",
    estimatedArrivalHome: "3:00 PM",
    totalTravelTimeMinutes: 120,
    timeline: [
      { id: "s1", time: "6:30 AM", title: "Leave home", kind: "depart", location: "New York, NY" },
      { id: "s2", time: "7:00 AM", title: "Arrive Penn Station", kind: "arrive" },
      { id: "s3", time: "7:15 AM", title: "LIRR train", kind: "transit", detail: "Penn Station → Sayville", durationMinutes: 75 },
      { id: "s4", time: "8:30 AM", title: "Arrive Sayville", kind: "arrive" },
      { id: "s5", time: "8:45 AM", title: "Fire Island Ferry", kind: "transit", detail: "Sayville → Sailors Haven", durationMinutes: 30 },
      { id: "s6", time: "9:15 AM", title: "Arrive at trailhead", kind: "arrive", note: "The ferry docks right at Sailors Haven." },
      { id: "s7", time: "9:30 AM", title: "Start hike", kind: "activity", detail: "Lighthouse Trail", durationMinutes: 90 },
      { id: "s8", time: "11:00 AM", title: "Finish hike / beach time", kind: "activity", note: "Sunken Forest boardwalk is a short, easy add-on nearby." },
      { id: "s9", time: "1:00 PM", title: "Begin return trip", kind: "return" },
      { id: "s10", time: "3:00 PM", title: "Arrive home", kind: "arrive" },
    ],
    transportationLegs: [
      {
        id: "leg1",
        mode: "transit",
        label: "LIRR",
        from: "Penn Station",
        to: "Sayville",
        departure: "7:15 AM",
        arrival: "8:30 AM",
        durationMinutes: 75,
        fare: 20,
        transferInfo: "No transfer — direct train.",
      },
      {
        id: "leg2",
        mode: "ferry",
        label: "Fire Island Ferry",
        from: "Sayville",
        to: "Sailors Haven",
        departure: "8:45 AM",
        arrival: "9:15 AM",
        durationMinutes: 30,
        fare: 12,
        transferInfo: "Ferries run on a fixed seasonal schedule — check departure times ahead.",
      },
    ],
    trailDayPlan: {
      trailName: "Lighthouse Trail",
      trailDistanceMiles: 3.0,
      estimatedDurationMinutes: 90,
      difficulty: "easy",
      elevationGainFeet: 40,
      suggestedStartTime: "9:30 AM",
      suggestedFinishTime: "11:00 AM",
      lunchWindow: "11:00 – 11:45 AM",
      checklist: CHECKLIST,
    },
    costBreakdown: [
      { label: "Transit", amount: 45 },
      { label: "Local transfer", amount: 10 },
      { label: "Food", amount: 40 },
      { label: "Buffer", amount: 35 },
    ],
    weatherWindows: [
      { label: "Morning", tempF: 58, condition: "Sunny" },
      { label: "Afternoon", tempF: 66, condition: "Breezy" },
    ],
    weatherRecommendation:
      "Warm and breezy by the water — bring a windbreaker for the ferry ride even if the trail feels warm.",
  },
];

export function getTripPlan(adventureId: string): TripPlan | undefined {
  return tripPlans.find((plan) => plan.adventureId === adventureId);
}
